### ISSUE TITLE
UPDATE 1.1 please

### ISSUE THREAD

**Issue by Obamavn99** [TesseractTeam/Tesseract#1135] opened 2017-06-03 12:09 UTC
#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by BlawoHD** [comment] 2017-06-03 12:59
Check #1128

**Comment by EoflaOE** [comment] 2017-06-03 13:05
Duplicate of #1128. Tesseract for MCPE 1.1 will be coming in few days. By the way this issue will be closed because there is not enough info.

**Closed by EoflaOE** 2017-06-03 13:05 UTC
