### ISSUE TITLE
Probleme to connect server

### ISSUE THREAD

**Issue by Barlaf** [TesseractTeam/Tesseract#971] opened 2017-04-21 17:30 UTC
#### Problem description

Hello, I can not connect to my server. When I connect I receive the message "Disconnect from the server". I then restarted the server several times. A solution to this problem? Cordially, Barlaf

* Tesseract: Tesseract-1.2.1 RottenApple
* PHP: 7.0.10
* Server OS: I don't know
* Game version: 1.0.7
* Server host: HostMyServer

**Comment by AffanStarPure** [comment] 2017-04-21 17:53
Yes same too I can not connect the Server

**Comment by PluginBOXone** [comment] 2017-04-21 18:11
Is there a message in the console like "RakLib crashed..." ?

**Comment by Barlaf** [comment] 2017-04-21 18:52
No, there is no "RackLib crash". The server normally works just can not connect to it

**Comment by PluginBOXone** [comment] 2017-04-21 19:18
Are you hosting on Linux or Windows?

**Comment by Jestus5225** [comment] 2017-04-21 19:29
I also have this **problem**!

**Comment by AppleDevelops** [comment] 2017-04-21 21:14
I'd help but I'm not a part of the repo.

**Comment by Barlaf** [comment] 2017-04-21 22:03
Her server is on Linux

**Comment by jrodr10** [comment] 2017-04-22 18:05
Is this due to the protocol hack?

**Comment by AffanStarPure** [comment] 2017-04-22 18:08
Idk but i cannot in game is said disconnected form Server that no error too

**Comment by AppleDevelops** [comment] 2017-04-22 18:24
I cannot reproduce it on the latest version.

**Comment by Barlaf** [comment] 2017-04-22 21:17
Hum... 
I found the problem. This is the PurePerm plugins (the one that handles the permissions) that causes the problem. So a solution because I used PurePerm to use PureChat

**Comment by FienixEC** [comment] 2017-04-23 00:01
are you using an outdated version of pure perms? i use the latest Perms/Pchat plugins, running the latest tesseract src, on linux OS and do not have that issue. i know theres a pureperms version out there with many issues

**Comment by imjayl** [comment] 2017-04-23 01:35
Why it would be the pureperm problem?

**Comment by FienixEC** [comment] 2017-04-23 02:27
I wouldnt think so either @imjayl . Come to think of it, its happened to me 2 times, (happened about 2 hours ago) where i cant connect to my server due to the same issue, i get the same message "unable to connect to world" and i pardon my ip, and im able to join right away. not sure why that happens as my ip doesnt show as banned in my ips.txt file during the time

**Comment by ZaydPE** [comment] 2017-04-23 06:44
Re-install PurePerms but bump it's API. PurePerms, CustomAlerts and more are widely used plugins with very old API's.

**Comment by MCPEGamerJPatGitHub** [comment] 2017-04-23 07:23
@ZaydPE Plugins does not seem to be the issue here. I am using a fresh install of Tesseract but the same issue exist.

**Comment by ZaydPE** [comment] 2017-04-23 07:54
It happened to me, I re-installed outdated API's and then everything was fine. Issue definitely happens because of PurePerms. Try removing PurePerms and joining

**Comment by AffanStarPure** [comment] 2017-04-23 09:03
I use old version Tesseract 1.0.6 all plugin work for me when Update 1.0.7 not work is said disconnected form Server

**Comment by NFGamerMC** [comment] 2017-04-23 10:58
Why not switch to BlueLight

**Comment by Barlaf** [comment] 2017-04-23 11:38
@NFGamerMC BlueLight ? And @imjayl When I remove PurePerm everything works correctly. My version of PurePerm is "1.4.0-INDEV" (I update the API) @FienixEC

**Comment by AffanStarPure** [comment] 2017-04-23 11:40
So PurePerms Problem Only?

**Comment by Barlaf** [comment] 2017-04-23 11:42
Yes @AffanStarPure when I delete PurePerm I can join my server

**Comment by AffanStarPure** [comment] 2017-04-23 11:48
Oh @Barlaf  Thank but where I can get PurePerms Work to on server Tesseract? Should I use old API or the new one? I need link too to get PurePerms

**Comment by Barlaf** [comment] 2017-04-23 11:55
@AffanStarPure For get open source PurePerm : 
https://github.com/PurePlugins/PurePerms/blob/master/plugin.yml
But me, I delete PurePerm. Idk who poses problem in pureperm

**Comment by FienixEC** [comment] 2017-04-23 19:23
@Barlaf email me at fienixjp@gmail.com ill send you my version of pureperms, install it and try

**Comment by jrodr10** [comment] 2017-04-24 05:22
So pureperms bug 🤔

**Comment by DerddyDert** [comment] 2017-04-25 11:51
I was able to reproduce this using the Pureperms available on poggit. That version is the one that caused the issue.

**Comment by imjayl** [comment] 2017-04-25 16:03
@DerddyDert im using the oldest pureperms but it's working on the previous tesseract version (1.0.4 to 1.0.6) .

**Comment by caspervanneck** [comment] 2017-04-25 16:29
yes its plugin bug i wiped my server and it working

**Comment by caspervanneck** [comment] 2017-04-25 17:29
@Barlaf downgrade pureperms and purechat that shult fix it i can give you the plugins

**Comment by caspervanneck** [comment] 2017-04-25 17:31
here pureperms fix replact the phar

**Comment by caspervanneck** [comment] 2017-04-25 17:32
https://drive.google.com/open?id=0B1Cw5aPWlm3iR3BjUEkyMjR0TmM

**Comment by DerddyDert** [comment] 2017-04-26 00:25
Im running pureperms 1.3.7 since I had the disconnect error. Works great.

**Comment by jrodr10** [comment] 2017-04-27 04:23
Same I had to redo my perm files. I wonder what the cause it thoe

**Comment by ImagicalGamer** [comment] 2017-04-28 19:33
Can you please get a PHP debug backtrace and put it on pastebin then put the link here.

**Comment by jrodr10** [comment] 2017-04-28 21:25
@Barlaf @AffanStarPure @PluginBOXone @Jestus5225

**Comment by imjayl** [comment] 2017-04-29 02:41
Its not pureperms. I used bluelight to test it.

1.0.6-1.0.7 can join the server with pureperms

**Comment by caspervanneck** [comment] 2017-04-29 06:00
@imjayl  we arent bluelight so yea

maby some thing have change in Tesseract or pureperms

**Comment by DerddyDert** [comment] 2017-04-29 06:17
@imjayl You tested with the Pureperms version that reproduces the problem?

**Comment by MCPEGamerJPatGitHub** [comment] 2017-04-29 09:45
I have no problem using the PurePerms v1.3.3 made for API 2.0.
I can join normally & have no issues.
Maybe you did something wrong?

**Comment by imjayl** [comment] 2017-04-29 13:02
@DerddyDert Yes

@MCPEGamerJPatGitHub using pureperms & 1.0.7 Tesseract?

**Comment by imjayl** [comment] 2017-04-29 13:05
Please use the last 1.0.6 Version and change its protocol to 1.0.7 and i will test it if its working with pureperms.

**Comment by MCPEGamerJPatGitHub** [comment] 2017-04-29 13:26
@imjayl yep, I don't think the new version of pureperms is stable so I use the old version.

**Comment by MCPEGamerJPatGitHub** [comment] 2017-04-29 13:27
to conclude this is a plugin issue.
we advise for someone to close this issue.

**Closed** 2017-04-29 14:54 UTC
Labels: C: Bug, C: Gameplay

**Comment by imjayl** [comment] 2017-04-29 16:22
Im using PurePerms 1.4.0. Can you give your copy of the old version?

**Comment by MCPEGamerJPatGitHub** [comment] 2017-04-29 22:42
@imjayl It is on the old PocketMine forums.
