### ISSUE TITLE
Sign Bugs

### ISSUE THREAD

**Issue by JunkDaCoder** [TesseractTeam/Tesseract#223] opened 2017-02-13 04:16 UTC
* Tesseract: 1.1.0
* PHP:7
* Server OS:Linux
* Game version: 1.0.3, Windows 10 ANd PE
* Server host:OVH
Players cant see signs i wrote and i cant place signs on wall they break insantly. To replicate the breaking signs issue, place on on a wall. For people not seeing it have them come right in front of u, place a sign with writing and they cant see the text

**Comment by RTGDaCoder** [comment] 2017-02-13 04:41
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/tile/Sign.php | I assume the updates from the original master isn't merged in this Tesseract Spoon.

**Comment by LordJoshie** [comment] 2017-02-13 09:52
I'm not having this issue.... same setup and host. Ubuntu 15.10  PHP 7.0.3  MCPE 1.0.3.  

latest version of Tess... my signs work. :/

**Comment by RTGDaCoder** [comment] 2017-02-13 11:25
Very odd... I'll test it on a normal Mulitcraft installation and update.

**Comment by LordJoshie** [comment] 2017-02-13 13:53
dont mind me asking, whats multi-craft?

**Comment by RTGDaCoder** [comment] 2017-02-13 14:15
It's a server hosting panel which allows you to host a server for free. You can create 10 Console accounts for free.
Hi

**Comment by LordJoshie** [comment] 2017-02-13 14:16
weak. but truu... okay.

I just use my vps from ovh.

**Comment by remotevase** [comment] 2017-02-14 22:03
Test again

**Comment by remotevase** [comment] 2017-02-14 22:06
never mind. Let me actually fix part of it.

**Comment by remotevase** [comment] 2017-02-14 22:43
Should be fixed. Please retest

**Comment by LordJoshie** [comment] 2017-02-14 23:50
I never had this issue, so I hope whatever you did didn't break anything.
Lol.

**Comment by remotevase** [comment] 2017-02-15 01:15
I def didnt break anything. Either I fixed it, or I kept it the same. XD

**Comment by remotevase** [comment] 2017-02-15 01:15
@LordJoshie I was mainly aiming for
1. I never had this issue, but if it can't be reproduced, great!
2. Sometimes the text on the sign disappears after typing it. I tried to fix that.

**Comment by LordJoshie** [comment] 2017-02-15 01:27
The text on sign disappears for me too, but only in areas that are really
built up or have a lot of players crowding around.

Anywhere else seems to be fine.

Might be a tick issue ?

But yeah, just hoping nothing gets rekt trying to fix an issue. :P

On Feb 14, 2017 8:15 PM, "remote_vase" <notifications@github.com> wrote:

@LordJoshie <https://github.com/LordJoshie> I was mainly aiming for

   1. I never had this issue, but if it can't be reproduced, great!
   2. Sometimes the text on the sign disappears after typing it. I tried to
   fix that.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/TesseractTeam/Tesseract/issues/223#issuecomment-279888825>,
or mute the thread

**Comment by remotevase** [comment] 2017-02-15 01:28
@LordJoshie I meant on the latest commit, not in the past XD

**Comment by JunkDaCoder** [comment] 2017-02-15 02:26
no signs still break if u place them on walls ,and i dont have another player on to test the invisible sign glitch for other players

**Comment by LordJoshie** [comment] 2017-02-15 02:27
Make an alt. ;) Thats how us pros do it.

Less reliance on reliable feedback.

**Comment by JunkDaCoder** [comment] 2017-02-15 02:29
no players still cant see it

**Comment by RTGDaCoder** [comment] 2017-02-15 08:10
Hi! I've tested again and the sign works as it should!

**Comment by remotevase** [comment] 2017-02-15 20:50
@RTGDaCoder Thanks so much!

**Closed** 2017-02-19 04:04 UTC
Labels: Bug, Waiting for a reply by O.P or Tester
