### ISSUE TITLE
Player already in "tablist" after disconnect!

### ISSUE THREAD

**Issue by Bluplayz** [TesseractTeam/Tesseract#204] opened 2017-02-10 14:51 UTC
#### Problem description

i tested the bug on my IOS Devices (IPhone 6s) and my Windows 10 Edition.
after a player disconnect from the server, all others who are actually online will see there name in tablist.

with tablist i mean the list of players next to the buttons like to main menu and options :D 

#### OS and versions

* Tesseract: Tesseract-1.1.0 Ruby
* PHP: 7.0.3
* Server OS: Debian 8
* Game version: 1.0.3
* Server host: Necror.de (VServer)
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AppleDevelops** [comment] 2017-02-10 16:35
Do you use EssentialsPE?

**Comment by erkam2002** [comment] 2017-02-10 16:46
i dont think that he is using essentialpe i know him :)

**Comment by AydarTop** [comment] 2017-02-10 17:01
I'm also have bag this tablist. Several columns empty. I don't use EssentialsPE.
![screenshot_20170210-195540](https://cloud.githubusercontent.com/assets/24245658/22835855/3812706a-efcb-11e6-9a2d-46093eb52ebe.png)

**Comment by erkam2002** [comment] 2017-02-10 17:57
See....

**Comment by Bluplayz** [comment] 2017-02-10 18:33
I dont use EssentialsPE :D i only use selfmade plugins

**Comment by AnkitM252** [comment] 2017-02-11 00:18
Try without any plugin

**Comment by remotevase** [comment] 2017-02-11 16:55
Confirmed with me as well

**Comment by ivan691** [comment] 2017-02-12 08:00
Havent't this

**Comment by remotevase** [comment] 2017-02-13 03:19
Really? It's confirmed by lots of people...

**Comment by Bluplayz** [comment] 2017-02-14 08:29
"Try without any plugin" - I tried but same problem

**Comment by remotevase** [comment] 2017-02-14 23:02
Please retest. Should be fixed.

**Comment by Bluplayz** [comment] 2017-02-15 07:40
i testet it but now there is another problem xD

now i am two times in the tablist ^^ problem doesnt fix and you added the bug that if you join, your name is two times in the tablist but i think its only visible to you ^^

**Comment by daniktheboss** [comment] 2017-02-15 15:59
This is a well known bug so might as well close it and take it as a feature

**Comment by remotevase** [comment] 2017-02-15 20:39
@Bluplayz there are a lot of "i think" in that. Please test with other players then tell again.

**Comment by Bluplayz** [comment] 2017-02-16 16:28
i tested it with 2 other people and all have the same problem lol

**Comment by Pizzahaet** [comment] 2017-02-17 15:31
This bug where you show up twice I seen seems to happen because PurePerms/PureChat inergrating FacPro and others, it's been a bug since 0.16 no one really thought much about it because it doesnt affect game much, I think mostly that it's because the server can't refresh your nametag in time and sync with tablist and others quick enough... (if this is really dumb what I said please reach through the web and smack me I give full consent that I won't sue lol)

**Comment by daniktheboss** [comment] 2017-02-17 15:35
@applepie... let's smack him now 😂😂

**Comment by Pizzahaet** [comment] 2017-02-17 18:49
@daniktheboss OK, do it sorry it didn't make sense I was using school pc with trash keyboard

**Comment by Pizzahaet** [comment] 2017-02-17 18:50
I was basically going off of what I experienced with this....

**Comment by Bluplayz** [comment] 2017-02-17 21:10
the issue doesnt comes from Tesseract, the issue comes from Nemisys lol


but now i get another issue xD if i join, i see myself 2 times in the tablist xD

**Closed** 2017-02-17 21:09 UTC
Labels: Bug, Confirmed, Waiting for a reply by O.P or Tester
