### ISSUE TITLE
getChunk on null

### ISSUE THREAD

**Issue by Driesboy** [TesseractTeam/Tesseract#211] opened 2017-02-11 11:52 UTC
#### Problem description

/

#### Steps to reproduce the issue

/

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/commit/d8cc0fd31f0b331539887ec10177529e2587b685
* PHP: 7.0.14
* Server OS: Windows
* Game version: 1.0.3
* Server host: SelfHosting
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Tesseract Crash Dump Sat Feb 11 12:51:03 CET 2017

Error: Call to a member function getChunk() on null
File: /src/pocketmine/level/Level
Line: 2698
Type: notice

Code:
[2689] 	public function loadChunk(int $x, int $z, bool $generate = true) : bool{
[2690] 		if(isset($this->chunks[$index = Level::chunkHash($x, $z)])){
[2691] 			return true;
[2692] 		}
[2693] 
[2694] 		$this->timings->syncChunkLoadTimer->startTiming();
[2695] 
[2696] 		$this->cancelUnloadChunkRequest($x, $z);
[2697] 
[2698] 		$chunk = $this->provider->getChunk($x, $z, $generate);
[2699] 		if($chunk === null){
[2700] 			if($generate){
[2701] 				throw new \InvalidStateException("Could not create new Chunk");
[2702] 			}
[2703] 			return false;
[2704] 		}
[2705] 
[2706] 		$this->chunks[$index] = $chunk;
[2707] 		$chunk->initChunk();
[2708] 

Backtrace:
#0 /src/pocketmine/Player(929): pocketmine\level\Level->registerChunkLoader(pocketmine\Player Player(18), integer 1628, integer -2, boolean 1)
#1 /src/pocketmine/Player(1861): pocketmine\Player->sendNextChunk(boolean)
#2 /src/pocketmine/Server(2716): pocketmine\Player->checkNetwork(boolean)
#3 /src/pocketmine/Server(2433): pocketmine\Server->tick(boolean)
#4 /src/pocketmine/Server(2312): pocketmine\Server->tickProcessor(boolean)
#5 /src/pocketmine/Server(1848): pocketmine\Server->start(boolean)
#6 /src/pocketmine/PocketMine(452): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\pc\Desktop\CubeCraftPE\, string C:\Users\pc\Desktop\CubeCraftPE\, string C:\Users\pc\Desktop\CubeCraftPE\plugins\, string unknown)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 101; API 3.0.0]
uname -a: Windows NT PC_VAN_PC 6.0 build 6002 (Windows Vista Business Edition Service Pack 2) i586
PHP version: 7.0.14
Zend version: 3.0.0
OS : WINNT, win

Server uptime: 7 minutes 14 seconds
Number of loaded worlds: 10
Players online: 24/50

Loaded plugins:
Online 1.5 by Ad5001 for API(s) 2.0.0
HereAuth 1.0-Beta#227 by PEMapModder for API(s) 2.0.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
EconomyAPI 2.0.9 by onebone for API(s) 3.0.0, 2.0.0, 2.1.0
PurePerms 1.4.0-INDEV by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
GMCPE-AntiCheat 3.2.0 by DarkWav for API(s) 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0
SW_svile 0.6dev by svile for API(s) 2.0.0, 2.1.0, 3.0.0-ALPHA1, 3.0.0
UChatP 1.0.0 by MCrafters for API(s) 2.0.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0, 2.0.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
WarnPlayer 1.0.0 by MCrafters for API(s) 2.0.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
```

**Comment by xZeroMCPE** [comment] 2017-02-11 15:45
Was it the default world? If not was the world loaded?

**Comment by Driesboy** [comment] 2017-02-11 15:47
i think its the enderpearl again
its only if a player have a enderpearl

**Comment by remotevase** [comment] 2017-02-11 16:52
I'm waiting for a fix... I think @Misteboss knows how to.

**Comment by remotevase** [comment] 2017-02-11 16:57
Duplicate of #153

**Closed** 2017-02-11 16:58 UTC
Labels: Bug, Chunk, Confirmed

**Comment by Driesboy** [comment] 2017-02-11 16:59
Ok
