### ISSUE TITLE
Server-Crash

### ISSUE THREAD

**Issue by Akuroma** [TesseractTeam/Tesseract#279] opened 2017-02-18 17:36 UTC
#### Problem description
Server crashes and creates a crashdump. Something with RegionLoader doesn't work. Crashdump seen below.

#### OS and versions

* Tesseract: Tesseract-1.1.0 (Codename "Ruby")
* PHP: 7.0.3
* Server OS: Linux (Ubuntu 14.04.5)
* Game version: 1.0.3
* Server host: VServer (root access via "putty"; FTP access via FileZilla)
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files
CRITICAL> TypeError: "ord() expects parameter 1 to be string, boolean given" (EXCEPTION) in "/src/pocketmine/level/format/io/region/RegionLoader" at line 79
```
```

**Comment by xZeroMCPE** [comment] 2017-02-21 04:34
Duplicate of #153

**Closed by xZeroMCPE** 2017-02-21 04:34 UTC
Labels: Bug, Unconfirmed, Waiting for a reply by O.P or Tester
