### ISSUE TITLE
Please Fix Logged Out Time Out

### ISSUE THREAD

**Issue by StormCraftMCPE** [TesseractTeam/Tesseract#1147] opened 2017-06-05 14:33 UTC
logged Out Due Timeout

**Comment by SuperKali** [comment] 2017-06-05 14:50
look here #1141

**Comment by daniktheboss** [comment] 2017-06-05 14:53
Duplicate... close

**Comment by SuperKali** [comment] 2017-06-05 15:02
yes

**Comment by jdongel2004** [comment] 2017-06-05 15:07
jrodr10 can't fix this issue.

**Comment by jrodr10** [comment] 2017-06-05 15:36
Duplicate of #1141

**Closed by jrodr10** 2017-06-05 15:36 UTC
