### ISSUE TITLE
terrain glitch

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [TesseractTeam/Tesseract#140] opened 2017-01-20 15:42 UTC
Just used last build! Becouse i saw terrain tweaks!
And i get this ! 0-0 
![screenshot_2017-01-20-17-38-34](https://cloud.githubusercontent.com/assets/18122629/22155368/dbd07f16-df37-11e6-8985-1ac286e49fea.png)

**Comment by remotevase** [comment] 2017-01-20 17:19
WOW!!! @AppleDevelops

**Comment by xZeroMCPE** [comment] 2017-01-20 17:59
@AppleDevelops lmao.... Really o.0

**Comment by LordJoshie** [comment] 2017-01-21 13:41
yah.... but is this 'glitch' still visible if you relog ?

**Comment by NemanjaMAX** [comment] 2017-01-22 14:52
Not Bug!!!
Close it and INVALID tag
Its glitch when you create new world (/mw create name 0 emptyworld).Translate:Chunks need load :D

**Comment by remotevase** [comment] 2017-01-23 03:05
@NemanjaMAX thanks, I was wondering why this happened because I was not able to reproduce it

**Closed by remotevase** 2017-01-23 03:05 UTC
Labels: Bug
