### ISSUE TITLE
You can't go on nether

### ISSUE THREAD

**Issue by poustmal** [TesseractTeam/Tesseract#480] opened 2017-04-03 14:37 UTC
Tesseract: 53b7b8a(I updated tesseract today)
Php: 7.0.3
Game version: 1.0.5(no beta,official) android

This happens when I'm trying to go to nether and my screen stucks on building terrain(bad english idk)

Warning: assert(): Unhandled player action 14 from Saxavlax001 failed in /storage/sdcard0/PocketMine/src/pocketmine/Player.php on line 2590

**Comment by poustmal** [comment] 2017-04-03 14:37
This was happening also here in older versions,1.0.4 etc

**Comment by LordJoshie** [comment] 2017-04-03 15:01
if you logout/login, you'll relog in the nether.

**Comment by NemanjaMAX** [comment] 2017-04-04 13:58
@AppleDevelops Close this..
All works fine. Maybe Plugin bug :)

**Comment by LordJoshie** [comment] 2017-04-04 16:27
only plugin id use that might have anything to do with this is manyworlds.

**Comment by poustmal** [comment] 2017-04-04 21:00
I'm using essentialspe,but on other software and version,nether was working,I think that sth is missing on tesseract

**Comment by AppleDevelops** [comment] 2017-04-04 21:16
I'll work on it in API 4

**Comment by NFGamerMC** [comment] 2017-04-06 21:00
This is something that is most likely happening in pocketmine.yml or tesseract.yml

**Comment by NFGamerMC** [comment] 2017-04-07 17:19
I am going to close this and mark it as invalid!

**Comment by poustmal** [comment] 2017-04-07 17:22
Yes,but I can't join!I can only try without plugins,but I don't think that this is the problem

**Comment by NFGamerMC** [comment] 2017-04-07 18:02
How about re-download Tesseract!

**Comment by NFGamerMC** [comment] 2017-04-07 18:03
Here is the link for the lates phar (1.0.5)

https://circleci-tkn.rhcloud.com/api/v1/project/TesseractTeam/Tesseract/tree/master/latest/artifacts/Tesseract_1.2.0.phar

**Comment by poustmal** [comment] 2017-04-07 18:08
Well,wait

**Comment by NFGamerMC** [comment] 2017-04-07 18:09
What?

**Comment by NFGamerMC** [comment] 2017-04-07 18:09
Try that and then see if you can join the nether also when the server is stopped just delete Pocketmine.yml

**Comment by poustmal** [comment] 2017-04-07 18:24
Again the same error and with deleted pocketmine.yml

**Comment by NFGamerMC** [comment] 2017-04-07 18:25
Are you useing a VPS or are you hosting it at home

**Comment by poustmal** [comment] 2017-04-07 18:31
Warning: assert(): Unhandled player action 14 from Saxavlax001 failed in phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/Player.php on line 2590

**Comment by poustmal** [comment] 2017-04-07 18:31
Im hosting it at home

**Comment by poustmal** [comment] 2017-04-07 18:32
But when I was using genisys,(older mcpe versions) mether was working idk

**Comment by NFGamerMC** [comment] 2017-04-07 18:32
My PHP is a bit rusty so I will look for errors but someone else may fix it

**Comment by NFGamerMC** [comment] 2017-04-07 18:32
So, you are on Genisys now?

**Comment by poustmal** [comment] 2017-04-07 18:33
No,im usong tesseract,i mean when i was using genisys 0.14-0.15 nether was working

**Comment by NFGamerMC** [comment] 2017-04-07 18:36
Just looked on the line and i see nothing related to nether portals just elytra!, the line seems to be intentionally saying that

**Closed** 2017-04-09 06:20 UTC
Labels: C: Bug, C: Gameplay, C: Unconfirmed, Help Wanted

**Comment by IrishPacks** [comment] 2017-04-17 20:39
Reopen this. The issue is that when changing dimensions, a PlayStatusPacket must be sent, otherwise the player will never be spawned in and will be stuck on the building terrain screen.
